'use client';

import { sortColors } from '@/lib/images';
import { useCallback, useEffect, useRef, useState } from 'react';

type Stir = { x: number; y: number; dx: number; dy: number; born: number };
const vertexShader=`attribute vec2 position;varying vec2 uv;void main(){uv=position*.5+.5;gl_Position=vec4(position,0.,1.);}`;
const fragmentShader=`precision mediump float;varying vec2 uv;uniform sampler2D palette;uniform float time;uniform float motion;uniform float aspect;uniform vec4 stirs[12];uniform float ages[12];float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){vec2 p=uv;if(motion>.5){float n1=noise(p*2.6+vec2(time*.055,-time*.038));float n2=noise(p*2.6+vec2(-time*.042,time*.05)+8.3);p+=(vec2(n1,n2)-.5)*.045;for(int i=0;i<12;i++){float age=ages[i];float life=max(0.,1.-age);vec2 velocity=stirs[i].zw;velocity.x/=aspect;vec2 center=stirs[i].xy+velocity*age*.075;vec2 d=p-center;d.x*=aspect;float r=length(d)+.003;float speed=min(2.,length(velocity));float fall=exp(-r*r*24.)*pow(life,.55);vec2 radial=d/r;vec2 tangent=vec2(-radial.y,radial.x);float rotation=sin(age*10.+r*9.)*.5+.5;p+=tangent*fall*(.025+speed*.075)*(rotation+.35);p-=velocity*fall*.095*exp(-age*2.2);p+=radial*sin(r*58.-age*30.)*fall*(.008+speed*.012);}}p=clamp(p,vec2(.002),vec2(.998));gl_FragColor=texture2D(palette,p);}`;
function compile(gl:WebGLRenderingContext,type:number,source:string){const shader=gl.createShader(type)!;gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(shader)||'Shader error');return shader}

export function FluidColorField({colors}:{colors:string[]}){
 const canvas=useRef<HTMLCanvasElement>(null),animation=useRef(0),stirs=useRef<Stir[]>([]),last=useRef({x:0,y:0,time:0}),lastStir=useRef(0),[motion,setMotion]=useState(true),[reduced,setReduced]=useState(false),[reset,setReset]=useState(0),sorted=sortColors(colors);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);if(media.matches)setMotion(false)};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 const stir=useCallback((clientX:number,clientY:number)=>{const c=canvas.current;if(!c||!motion||reduced)return;const rect=c.getBoundingClientRect(),now=performance.now(),x=(clientX-rect.left)/rect.width,y=1-(clientY-rect.top)/rect.height,elapsed=Math.max(12,now-last.current.time),dx=(x-last.current.x)*1000/elapsed,dy=(y-last.current.y)*1000/elapsed;last.current={x,y,time:now};if(now-lastStir.current>48&&Math.hypot(dx,dy)>.015){lastStir.current=now;stirs.current.push({x,y,dx:Math.max(-2,Math.min(2,dx)),dy:Math.max(-2,Math.min(2,dy)),born:now});stirs.current=stirs.current.slice(-12)}},[motion,reduced]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const gl=c.getContext('webgl',{antialias:false,alpha:false,powerPreference:'high-performance'});if(!gl)return;const program=gl.createProgram()!;gl.attachShader(program,compile(gl,gl.VERTEX_SHADER,vertexShader));gl.attachShader(program,compile(gl,gl.FRAGMENT_SHADER,fragmentShader));gl.linkProgram(program);gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const position=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,2,gl.FLOAT,false,0,0);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
  const resize=()=>{const width=c.clientWidth,height=c.clientHeight,d=Math.min(devicePixelRatio,.8);c.width=Math.round(width*d);c.height=Math.round(height*d);gl.viewport(0,0,c.width,c.height);const columns=innerWidth>=1024?6:innerWidth>=640?4:3,rows=Math.ceil(sorted.length/columns),pixels=new Uint8Array(columns*rows*4);for(let row=0;row<rows;row++)for(let col=0;col<columns;col++){const sourceRow=rows-1-row,index=sourceRow*columns+col,color=sorted[Math.min(index,sorted.length-1)]||'#777777',at=(row*columns+col)*4;pixels[at]=parseInt(color.slice(1,3),16);pixels[at+1]=parseInt(color.slice(3,5),16);pixels[at+2]=parseInt(color.slice(5,7),16);pixels[at+3]=255}gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,columns,rows,0,gl.RGBA,gl.UNSIGNED_BYTE,pixels)};
  resize();addEventListener('resize',resize);const started=performance.now(),timeLoc=gl.getUniformLocation(program,'time'),motionLoc=gl.getUniformLocation(program,'motion'),aspectLoc=gl.getUniformLocation(program,'aspect'),stirLoc=gl.getUniformLocation(program,'stirs'),ageLoc=gl.getUniformLocation(program,'ages');const draw=(now:number)=>{const active=stirs.current.filter(s=>now-s.born<14000);stirs.current=active;const values=new Float32Array(48),ages=new Float32Array(12).fill(2);active.forEach((s,i)=>{values.set([s.x,s.y,s.dx,s.dy],i*4);ages[i]=(now-s.born)/14000});gl.uniform1f(timeLoc,(now-started)/1000);gl.uniform1f(motionLoc,motion&&!reduced?1:0);gl.uniform1f(aspectLoc,c.clientWidth/c.clientHeight);gl.uniform4fv(stirLoc,values);gl.uniform1fv(ageLoc,ages);gl.drawArrays(gl.TRIANGLES,0,6);animation.current=requestAnimationFrame(draw)};animation.current=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(animation.current);removeEventListener('resize',resize);gl.deleteTexture(texture);gl.deleteProgram(program);gl.deleteBuffer(buffer)}},[sorted.join(','),motion,reduced,reset]);
 return <div className="relative h-[calc(100dvh-4rem)] overflow-hidden bg-neutral-500"><canvas ref={canvas} className="block h-full w-full touch-none" aria-label="Interactive mesh gradient made from archived sky colors" onPointerMove={e=>stir(e.clientX,e.clientY)} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();last.current={x:(e.clientX-r.left)/r.width,y:1-(e.clientY-r.top)/r.height,time:performance.now()}}}/><div className="pointer-events-none absolute bottom-4 left-5 text-[10px] text-white/80 mix-blend-difference">{reduced?'Static field · reduced motion':'Move to stir the sky'}</div><div className="absolute bottom-4 right-5 flex gap-5 text-[11px] text-white mix-blend-difference"><button onClick={()=>{stirs.current=[];setReset(x=>x+1)}}>Reset</button>{!reduced&&<button onClick={()=>setMotion(x=>!x)}>Motion: {motion?'On':'Off'}</button>}</div></div>
}
