'use client';

import { sortColors } from '@/lib/images';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

type ArtSettings={flow:number;swirl:number;brushSize:number;pointerForce:number;ambientDrift:number;viscosity:number;colorSoftness:number;paused:boolean};
type AdvancedSettings={simResolution:number;dyeResolution:number;pressureIterations:number};
type Pointer={x:number;y:number;dx:number;dy:number;moved:boolean;last:number};
type GLTarget={texture:WebGLTexture;fbo:WebGLFramebuffer;width:number;height:number};
type DoubleTarget={read:GLTarget;write:GLTarget;swap:()=>void};

const presets:Record<'CALM'|'SILK'|'MARBLE',ArtSettings>={
 CALM:{flow:.975,swirl:5,brushSize:.13,pointerForce:.75,ambientDrift:.018,viscosity:.32,colorSoftness:.7,paused:false},
 SILK:{flow:.987,swirl:11,brushSize:.105,pointerForce:1.35,ambientDrift:.03,viscosity:.2,colorSoftness:.48,paused:false},
 MARBLE:{flow:.993,swirl:17,brushSize:.085,pointerForce:1.75,ambientDrift:.038,viscosity:.1,colorSoftness:.3,paused:false},
};
const vertex=`#version 300 es
in vec2 position;out vec2 uv;void main(){uv=position*.5+.5;gl_Position=vec4(position,0.,1.);}`;
const shaders={
 copy:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D source;out vec4 outColor;void main(){outColor=texture(source,uv);}`,
 init:`#version 300 es
precision highp float;in vec2 uv;uniform vec3 colors[8];uniform float aspect;out vec4 outColor;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=a*noise(p);p=p*2.03+2.7;a*=.5;}return v;}
void main(){vec2 q=uv;q+=vec2(fbm(uv*1.2+3.1),fbm(uv*1.4+9.7)-.5)*.09;vec2 centers[8];centers[0]=vec2(-.15,.15);centers[1]=vec2(.22,.82);centers[2]=vec2(.62,1.12);centers[3]=vec2(1.15,.82);centers[4]=vec2(.9,.15);centers[5]=vec2(.48,.48);centers[6]=vec2(.05,1.15);centers[7]=vec2(1.18,-.12);float radii[8];radii[0]=.72;radii[1]=.58;radii[2]=.76;radii[3]=.69;radii[4]=.62;radii[5]=.48;radii[6]=.82;radii[7]=.88;vec3 sum=vec3(0);float total=0.;for(int i=0;i<8;i++){vec2 d=q-centers[i];d.x*=aspect;float w=exp(-dot(d,d)/(radii[i]*radii[i]));w*=.82+.28*fbm(q*1.35+float(i)*2.1);sum+=colors[i]*w;total+=w;}outColor=vec4(sum/max(total,.001),1.);}`,
 advect:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D velocity;uniform sampler2D source;uniform vec2 texel;uniform float dt;uniform float dissipation;uniform float viscosity;out vec4 outColor;
void main(){vec2 v=texture(velocity,uv).xy;vec2 coord=clamp(uv-dt*v,texel*.5,vec2(1.)-texel*.5);vec4 c=texture(source,coord);if(viscosity>0.){vec4 near=(texture(source,coord+vec2(texel.x,0))+texture(source,coord-vec2(texel.x,0))+texture(source,coord+vec2(0,texel.y))+texture(source,coord-vec2(0,texel.y)))*.25;c=mix(c,near,viscosity);}outColor=c/(1.+dissipation*dt);}`,
 splat:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D target;uniform vec2 point;uniform vec2 force;uniform float radius;uniform float aspect;out vec4 outColor;void main(){vec2 d=uv-point;d.x*=aspect;float influence=exp(-dot(d,d)/(radius*radius));vec4 base=texture(target,uv);outColor=vec4(base.xy+force*influence,base.zw);}`,
 ambient:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D velocity;uniform float time;uniform float strength;out vec4 outColor;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){float e=.006;vec2 p=uv*1.35+vec2(time*.021,-time*.016);float nx=noise(p+vec2(e,0))-noise(p-vec2(e,0));float ny=noise(p+vec2(0,e))-noise(p-vec2(0,e));vec2 curl=vec2(ny,-nx)/e;outColor=vec4(texture(velocity,uv).xy+curl*strength*.00022,0,1);}`,
 curl:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D velocity;uniform vec2 texel;out vec4 outColor;void main(){float l=texture(velocity,uv-vec2(texel.x,0)).y,r=texture(velocity,uv+vec2(texel.x,0)).y,b=texture(velocity,uv-vec2(0,texel.y)).x,t=texture(velocity,uv+vec2(0,texel.y)).x;outColor=vec4(.5*(r-l-b+t),0,0,1);}`,
 vorticity:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D velocity;uniform sampler2D curlTex;uniform vec2 texel;uniform float curlStrength;uniform float dt;out vec4 outColor;void main(){float l=abs(texture(curlTex,uv-vec2(texel.x,0)).x),r=abs(texture(curlTex,uv+vec2(texel.x,0)).x),b=abs(texture(curlTex,uv-vec2(0,texel.y)).x),t=abs(texture(curlTex,uv+vec2(0,texel.y)).x),c=texture(curlTex,uv).x;vec2 f=.5*vec2(t-b,r-l);f/=length(f)+.0001;f*=curlStrength*c;vec2 v=texture(velocity,uv).xy+f*dt;outColor=vec4(clamp(v,vec2(-2),vec2(2)),0,1);}`,
 divergence:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D velocity;uniform vec2 texel;out vec4 outColor;void main(){float l=texture(velocity,uv-vec2(texel.x,0)).x,r=texture(velocity,uv+vec2(texel.x,0)).x,b=texture(velocity,uv-vec2(0,texel.y)).y,t=texture(velocity,uv+vec2(0,texel.y)).y;outColor=vec4(.5*(r-l+t-b),0,0,1);}`,
 pressure:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D pressure;uniform sampler2D divergence;uniform vec2 texel;out vec4 outColor;void main(){float l=texture(pressure,uv-vec2(texel.x,0)).x,r=texture(pressure,uv+vec2(texel.x,0)).x,b=texture(pressure,uv-vec2(0,texel.y)).x,t=texture(pressure,uv+vec2(0,texel.y)).x,d=texture(divergence,uv).x;outColor=vec4((l+r+b+t-d)*.25,0,0,1);}`,
 gradient:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D pressure;uniform sampler2D velocity;uniform vec2 texel;uniform float pressureStrength;out vec4 outColor;void main(){float l=texture(pressure,uv-vec2(texel.x,0)).x,r=texture(pressure,uv+vec2(texel.x,0)).x,b=texture(pressure,uv-vec2(0,texel.y)).x,t=texture(pressure,uv+vec2(0,texel.y)).x;vec2 v=texture(velocity,uv).xy-vec2(r-l,t-b)*pressureStrength;outColor=vec4(v,0,1);}`,
 display:`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D dye;uniform vec2 texel;uniform float softness;out vec4 outColor;void main(){vec4 c=texture(dye,uv);vec4 blur=(texture(dye,uv+vec2(texel.x,0))+texture(dye,uv-vec2(texel.x,0))+texture(dye,uv+vec2(0,texel.y))+texture(dye,uv-vec2(0,texel.y)))*.25;outColor=vec4(mix(c.rgb,blur.rgb,softness),1);}`,
};

function Range({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void}){const p=(value-min)/(max-min)*100;return <label className="grid grid-cols-[1fr_58px] items-center gap-3 border-t border-white/10 px-4 py-2.5"><span><span className="mb-1.5 block text-[10px] uppercase tracking-[.12em] text-white/65">{label}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="block h-1 w-full cursor-pointer accent-sky-400" style={{background:`linear-gradient(90deg,#72b9d7 ${p}%,#363636 ${p}%)`}}/></span><output className="bg-white/10 px-2 py-1 text-right text-[10px] tabular-nums text-sky-200">{value}</output></label>}
function representative(colors:string[]){const sorted=sortColors(colors);return Array.from({length:8},(_,i)=>sorted[Math.min(sorted.length-1,Math.floor((i+.35)*sorted.length/8))]||'#7E8FA8')}

export function FluidColorField({colors}:{colors:string[]}){
 const canvas=useRef<HTMLCanvasElement>(null),raf=useRef(0),pointer=useRef<Pointer>({x:.5,y:.5,dx:0,dy:0,moved:false,last:0});
 const [settings,setSettings]=useState<ArtSettings>(presets.SILK),settingsRef=useRef(settings),[advanced,setAdvanced]=useState<AdvancedSettings>({simResolution:128,dyeResolution:768,pressureIterations:22}),advancedRef=useRef(advanced),[panel,setPanel]=useState(false),[advancedOpen,setAdvancedOpen]=useState(false),[preset,setPreset]=useState<'CALM'|'SILK'|'MARBLE'|null>('SILK'),[reset,setReset]=useState(0),[reduced,setReduced]=useState(false),palette=useMemo(()=>representative(colors),[colors]);
 settingsRef.current=settings;advancedRef.current=advanced;
 const set=<K extends keyof ArtSettings>(key:K,value:ArtSettings[K])=>{setPreset(null);setSettings(s=>({...s,[key]:value}))};
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);if(media.matches)setSettings(s=>({...s,paused:true}))};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 const move=useCallback((clientX:number,clientY:number)=>{const c=canvas.current,s=settingsRef.current;if(!c||s.paused||reduced)return;const r=c.getBoundingClientRect(),now=performance.now(),x=(clientX-r.left)/r.width,y=1-(clientY-r.top)/r.height,p=pointer.current,dt=Math.max(12,now-p.last),dx=(x-p.x)*1000/dt,dy=(y-p.y)*1000/dt;p.x=x;p.y=y;p.last=now;p.dx=Math.max(-2,Math.min(2,dx));p.dy=Math.max(-2,Math.min(2,dy));p.moved=Math.hypot(p.dx,p.dy)>.008},[reduced]);
 useEffect(()=>{const canvasEl=canvas.current;if(!canvasEl)return;const gl=canvasEl.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!gl||!gl.getExtension('EXT_color_buffer_float'))return;const linear=!!gl.getExtension('OES_texture_float_linear');
  const compile=(type:number,source:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'Shader error');return s};
  const programs=Object.fromEntries(Object.entries(shaders).map(([name,frag])=>{const p=gl.createProgram()!;gl.attachShader(p,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,frag));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)||'Program error');return[name,p]})) as Record<string,WebGLProgram>;
  const vao=gl.createVertexArray();gl.bindVertexArray(vao);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);for(const p of Object.values(programs)){const loc=gl.getAttribLocation(p,'position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0)}
  const makeTarget=(w:number,h:number,internal:number,format:number,filter:number)=>{const texture=gl.createTexture()!;gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,filter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,filter);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,internal,w,h,0,format,gl.HALF_FLOAT,null);const fbo=gl.createFramebuffer()!;gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);return{texture,fbo,width:w,height:h}};
  const makeDouble=(w:number,h:number,internal:number,format:number,filter:number):DoubleTarget=>{let read=makeTarget(w,h,internal,format,filter),write=makeTarget(w,h,internal,format,filter);return{get read(){return read},get write(){return write},swap(){const t=read;read=write;write=t}}};
  const sim=advancedRef.current.simResolution,dyeLong=innerWidth<640?Math.min(512,advancedRef.current.dyeResolution):advancedRef.current.dyeResolution,aspect=canvasEl.clientWidth/canvasEl.clientHeight,simW=aspect>1?Math.round(sim*aspect):sim,simH=aspect>1?sim:Math.round(sim/aspect),dyeW=aspect>1?Math.round(dyeLong*aspect):dyeLong,dyeH=aspect>1?dyeLong:Math.round(dyeLong/aspect),filter=linear?gl.LINEAR:gl.NEAREST;
  const velocity=makeDouble(simW,simH,gl.RG16F,gl.RG,filter),dye=makeDouble(dyeW,dyeH,gl.RGBA16F,gl.RGBA,filter),curl=makeTarget(simW,simH,gl.R16F,gl.RED,gl.NEAREST),divergence=makeTarget(simW,simH,gl.R16F,gl.RED,gl.NEAREST),pressure=makeDouble(simW,simH,gl.R16F,gl.RED,gl.NEAREST);
  const use=(name:string,target:GLTarget|null,uniforms:Record<string,number|number[]|WebGLTexture>)=>{const p=programs[name];gl.useProgram(p);let unit=0;for(const [key,value] of Object.entries(uniforms)){const loc=gl.getUniformLocation(p,key);if(value instanceof WebGLTexture){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,value);gl.uniform1i(loc,unit++)}else if(Array.isArray(value)){if(value.length===2)gl.uniform2f(loc,value[0],value[1]);else if(value.length===3)gl.uniform3f(loc,value[0],value[1],value[2]);else gl.uniform3fv(loc,value)}else gl.uniform1f(loc,value)}gl.bindFramebuffer(gl.FRAMEBUFFER,target?.fbo||null);gl.viewport(0,0,target?.width||canvasEl.width,target?.height||canvasEl.height);gl.drawArrays(gl.TRIANGLES,0,6)};
  const rgb=palette.flatMap(hex=>[parseInt(hex.slice(1,3),16)/255,parseInt(hex.slice(3,5),16)/255,parseInt(hex.slice(5,7),16)/255]);use('init',dye.read,{colors:rgb,aspect});use('copy',dye.write,{source:dye.read.texture});dye.swap();
  const resizeCanvas=()=>{const d=Math.min(devicePixelRatio,1.5);canvasEl.width=Math.round(canvasEl.clientWidth*d);canvasEl.height=Math.round(canvasEl.clientHeight*d)};resizeCanvas();addEventListener('resize',resizeCanvas);let previous=performance.now(),elapsed=0;
  const frame=(now:number)=>{const s=settingsRef.current,a=advancedRef.current,dt=Math.min(.018,(now-previous)/1000);previous=now;elapsed+=dt;if(!s.paused&&!reduced){const simTexel:[number,number]=[1/simW,1/simH];use('advect',velocity.write,{velocity:velocity.read.texture,source:velocity.read.texture,texel:simTexel,dt,dissipation:(1-s.flow)*7,viscosity:s.viscosity*.14});velocity.swap();use('ambient',velocity.write,{velocity:velocity.read.texture,time:elapsed,strength:s.ambientDrift});velocity.swap();const p=pointer.current;if(p.moved){use('splat',velocity.write,{target:velocity.read.texture,point:[p.x,p.y],force:[p.dx*s.pointerForce*.085,p.dy*s.pointerForce*.085],radius:s.brushSize,aspect});velocity.swap();p.moved=false}use('curl',curl,{velocity:velocity.read.texture,texel:simTexel});use('vorticity',velocity.write,{velocity:velocity.read.texture,curlTex:curl.texture,texel:simTexel,curlStrength:s.swirl,dt});velocity.swap();use('divergence',divergence,{velocity:velocity.read.texture,texel:simTexel});gl.bindFramebuffer(gl.FRAMEBUFFER,pressure.read.fbo);gl.viewport(0,0,simW,simH);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT);for(let i=0;i<a.pressureIterations;i++){use('pressure',pressure.write,{pressure:pressure.read.texture,divergence:divergence.texture,texel:simTexel});pressure.swap()}use('gradient',velocity.write,{pressure:pressure.read.texture,velocity:velocity.read.texture,texel:simTexel,pressureStrength:.8});velocity.swap();use('advect',dye.write,{velocity:velocity.read.texture,source:dye.read.texture,texel:[1/dyeW,1/dyeH],dt,dissipation:.00002,viscosity:0});dye.swap()}use('display',null,{dye:dye.read.texture,texel:[1/dyeW,1/dyeH],softness:s.colorSoftness});raf.current=requestAnimationFrame(frame)};raf.current=requestAnimationFrame(frame);
  return()=>{cancelAnimationFrame(raf.current);removeEventListener('resize',resizeCanvas);gl.getExtension('WEBGL_lose_context')?.loseContext()}
 },[palette.join(','),advanced.simResolution,advanced.dyeResolution,advanced.pressureIterations,reset,reduced]);
 const choose=(name:'CALM'|'SILK'|'MARBLE')=>{setPreset(name);setSettings({...presets[name],paused:reduced})};
 const changeAdvanced=<K extends keyof AdvancedSettings>(key:K,value:AdvancedSettings[K])=>setAdvanced(a=>({...a,[key]:value}));
 return <div className="relative h-[calc(100dvh-4rem)] overflow-hidden bg-neutral-500"><canvas ref={canvas} className="block h-full w-full touch-none" aria-label="Interactive fluid field made from archived sky colors" onPointerMove={e=>move(e.clientX,e.clientY)} onPointerDown={e=>move(e.clientX,e.clientY)}/>
  {panel&&<aside aria-label="Fluid settings" className="absolute right-4 top-4 z-20 max-h-[calc(100%-4.5rem)] w-[min(330px,calc(100vw-2rem))] overflow-auto bg-[#111]/95 text-white shadow-2xl backdrop-blur-md"><div className="flex items-center justify-between px-4 py-3"><span className="site-mark text-[11px] font-semibold tracking-[.14em]">FLUID SETTINGS</span><button onClick={()=>setPanel(false)} className="text-lg text-white/60">×</button></div><div className="grid grid-cols-3 gap-1 border-t border-white/10 p-2">{(['CALM','SILK','MARBLE'] as const).map(name=><button key={name} onClick={()=>choose(name)} className={`site-mark px-2 py-2 text-[9px] tracking-[.12em] ${preset===name?'bg-white text-black':'bg-white/5 text-white/65'}`}>{name}</button>)}</div>
   <Range label="Flow" value={settings.flow} min={.94} max={.998} step={.001} onChange={v=>set('flow',v)}/><Range label="Swirl" value={settings.swirl} min={0} max={25} step={1} onChange={v=>set('swirl',v)}/><Range label="Brush size" value={settings.brushSize} min={.04} max={.2} step={.005} onChange={v=>set('brushSize',v)}/><Range label="Pointer force" value={settings.pointerForce} min={.2} max={2.8} step={.05} onChange={v=>set('pointerForce',v)}/><Range label="Ambient drift" value={settings.ambientDrift} min={0} max={.08} step={.002} onChange={v=>set('ambientDrift',v)}/><Range label="Viscosity" value={settings.viscosity} min={0} max={.6} step={.02} onChange={v=>set('viscosity',v)}/><Range label="Color softness" value={settings.colorSoftness} min={0} max={1} step={.05} onChange={v=>set('colorSoftness',v)}/><label className="flex items-center justify-between border-t border-white/10 px-4 py-3 text-[10px] uppercase tracking-[.12em] text-white/65"><span>Paused</span><input type="checkbox" checked={settings.paused} disabled={reduced} onChange={e=>set('paused',e.target.checked)} className="accent-sky-500"/></label>
   <button onClick={()=>setAdvancedOpen(x=>!x)} className="flex w-full justify-between border-t border-white/10 px-4 py-3 text-[10px] uppercase tracking-[.12em] text-white/65"><span>Advanced</span><span>{advancedOpen?'−':'+'}</span></button>{advancedOpen&&<div><label className="grid grid-cols-2 items-center border-t border-white/10 px-4 py-2.5 text-[10px] uppercase tracking-[.1em] text-white/65"><span>Sim resolution</span><select value={advanced.simResolution} onChange={e=>changeAdvanced('simResolution',Number(e.target.value))} className="bg-white/10 px-2 py-1.5 text-white"><option className="text-black">64</option><option className="text-black">128</option><option className="text-black">192</option></select></label><label className="grid grid-cols-2 items-center border-t border-white/10 px-4 py-2.5 text-[10px] uppercase tracking-[.1em] text-white/65"><span>Dye resolution</span><select value={advanced.dyeResolution} onChange={e=>changeAdvanced('dyeResolution',Number(e.target.value))} className="bg-white/10 px-2 py-1.5 text-white"><option className="text-black">512</option><option className="text-black">768</option><option className="text-black">1024</option></select></label><Range label="Pressure iterations" value={advanced.pressureIterations} min={10} max={30} step={1} onChange={v=>changeAdvanced('pressureIterations',v)}/></div>}</aside>}
  <div className="pointer-events-none absolute bottom-4 left-5 text-[10px] text-white/80 mix-blend-difference">{reduced?'Static field · reduced motion':'Move through the color'}</div><div className="absolute bottom-4 right-5 flex gap-5 text-[11px] text-white mix-blend-difference"><button onClick={()=>setReset(x=>x+1)}>Reset</button><button onClick={()=>setPanel(x=>!x)}>Settings</button></div></div>
}
